apiVersion: v2
name: sealed-secrets-install
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

dependencies:
  # https://github.com/bitnami-labs/sealed-secrets/releases
  - name: sealed-secrets
    version: v2.17.1
    repository: https://bitnami-labs.github.io/sealed-secrets
