sealed-secrets:
  fullnameOverride: sealed-secrets-controller
  serviceAccount:
    create: true
  rbac:
    create: true
    clusterRole: true
  resources:
    limits:
      cpu: 150m
      memory: 256Mi
