sealed-secrets:
  fullnameOverride: sealed-secrets-controller
  keyrenewperiod: "0"  # Disable key renewal
  serviceAccount:
    create: true
  rbac:
    create: true
    clusterRole: true
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      memory: 256Mi
  podSecurityContext:
    enabled: true
    seccompProfile:
      type: "RuntimeDefault"
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  livenessProbe:
    initialDelaySeconds: 1
  readinessProbe:
    initialDelaySeconds: 1
