{{- if .Values.api.use }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-config:api-patcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.api.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.api.serviceAccount }}
    namespace: {{ .Release.Namespace }}
{{- end }}
