{{- if .Values.api.use }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.api.clusterRoleName }}
rules:
  - apiGroups:
      - "config.openshift.io"
    resources:
      - apiservers
    verbs:
      - get
      - list
      - watch
      - patch
{{- end }}
