apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-grafana-sa-token
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name}}-grafana-sa
type: kubernetes.io/service-account-token
