quota:
  use: false

upstream:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      memory: 64Mi
  nfs:
    server: 192.168.60.20
    path: /kube-volumes/nfs
  storageClass:
    name: nfs-provider
    defaultClass: true
  serviceAccount:
    create: true
    name: nfs-pod-provisioner-sa
