apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: compliance-operator-sub
  namespace: "{{ .Release.Namespace }}"
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: compliance-operator
  source: compliance-operator
  sourceNamespace: openshift-marketplace
