machineConfigs:
  enableProtectKernelSysctl:
    enabled: false # This does not work on Fedora CoreOS, nor RHCOS.

kubeletConfigs:
  enabled: true
  autosizeReserved:
    enabled: true
  tlsCipherSuites:
    enabled: true
  makeIPTablesUtilChains:
    enabled: true
  streamingConnectionIdleTimeout:
    enabled: true
  eventRecordQPS:
    enabled: true
  evictionConfig:
    enabled: true
  evictionSoft:
    enabled: true
  evictionHard:
    enabled: true
  protectKernelDefaults:
    enabled: false # this is a problem for both FCOS and RHCOS.

system:
  chrony:
    enabled: true
  extensions:
    usbGuard: false # Package usbguard does not exist for FCOS
  timezone:
    enabled: true

machineConfigPools:
  - master
  - worker

