machineConfigs:
  enableProtectKernelSysctl:
    enabled: false # This does not work on Fedora CoreOS, nor RHCOS.

kubeletConfigs:
  enabled: true
  autosizeReserved:
    enabled: true
    targetMachineConfigPools:
      - master
      - worker
  tlsCipherSuites:
    enabled: true
    targetMachineConfigPools:
      - master
      - worker
  makeIPTablesUtilChains:
    enabled: true
    targetMachineConfigPools:
      - master
      - worker
  streamingConnectionIdleTimeout:
    enabled: true
    targetMachineConfigPools:
      - master
      - worker
  eventRecordQPS:
    enabled: true
    targetMachineConfigPools:
      - master
      - worker
  evictionConfig:
    enabled: true
    targetMachineConfigPools:
      - master
      - worker
  evictionSoft:
    enabled: true
    targetMachineConfigPools:
      - master
      - worker
  evictionHard:
    enabled: true
    targetMachineConfigPools:
      - master
      - worker
  protectKernelDefaults:
    enabled: false # this is a problem for both FCOS and RHCOS.
    targetMachineConfigPools: []

system:
  chrony:
    enabled: true
  extensions:
    usbGuard: false # Package usbguard does not exist for FCOS
  timezone:
    enabled: true

machineConfigPools:
  - master
  - worker

