{{- if and (.Capabilities.APIVersions.Has "compliance.openshift.io/v1alpha1") -}}
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: smuda-ocp4-cis
spec:
  description: Tailored profile of ocp4-cis
  title: smuda-ocp4-cis
  extends: ocp4-cis
{{- end -}}
