{{- if and (.Capabilities.APIVersions.Has "compliance.openshift.io/v1alpha1") -}}
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: smuda-ocp4-cis-node
spec:
  description: Tailored profile of ocp4-cis-node
  title: ocp4-cis-node
  extends: ocp4-cis-node
{{- end -}}
