{{- if .Values.system.timezone.enabled -}}
{{- range $mcpName := .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: "99-timezone-{{ $mcpName }}"
  labels:
    machineconfiguration.openshift.io/role: {{ $mcpName }}
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=set timezone
            After=network-online.target

            [Service]
            Type=oneshot
            ExecStart=timedatectl set-timezone Europe/Stockholm

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: custom-timezone.service
---
{{- end -}}
{{- end -}}
