apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.openshiftConfig.clusterRole.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Values.openshiftConfig.clusterRole.name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.openshiftConfig.serviceAccount.name }}"
    namespace: "{{ .Release.Namespace }}"
