apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.openshiftConfig.clusterRole.name }}"
rules:
  # To label and annotate the MachineConfigPools
  - apiGroups:
      - machineconfiguration.openshift.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  # To setup OAuth with github
  - apiGroups:
      - config.openshift.io
    resources:
      - 'oauths'
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  # To setup OAuth with github, the operator needs to be able to list and watch on cluster scale
  - apiGroups:
      - ''
    resources:
      - 'secrets'
    verbs:
      - list
      - watch
