apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.openshiftConfig.role.name }}"
rules:
  - apiGroups:
      - redhatcop.redhat.io
    resources:
      - '*'
    verbs:
      - '*'
