apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.openshiftConfig.clusterRole.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ .Values.openshiftConfig.role.name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.openshiftConfig.serviceAccount.name }}"
    namespace: "{{ .Release.Namespace }}"
