{{ if .Values.egressIp.use }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: egressip-hostsubnets
  annotations:
    argocd.argoproj.io/sync-wave: "10" # Need to be after patch operator
spec:
  serviceAccountRef:
    name: {{ .Values.egressIp.serviceAccount }}
  patches:
    {{- range .Values.egressIp.hosts }}
    {{ .name }}:
      targetObjectRef:
        apiVersion: network.openshift.io/v1
        kind: HostSubnet
        name: {{ .name }}
      patchTemplate: |
        egressCIDRs:
          {{- range .subnets }}
          - {{ . }}
          {{- end }}
      patchType: application/merge-patch+json
    {{- end }}
{{- end }}
