apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asdf
  template:
    metadata:
      labels:
        app: asdf
    spec:
      containers:
        - name: nginx
          image: nginx
