{{ if .Values.networkpolicy.use }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name}}-default-deny-all
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
{{ end }}
