{{- if .Values.isOpenshift -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-instance-sa
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-instance-route"}}'
secrets:
  - name: grafana-instance-sa-token
{{- end }}
