{{- if .Values.isOpenshift }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  annotations:
    kubernetes.io/service-account.name: grafana-sa
  name: grafana-sa-token
{{- end }}
