upstream:
  reloader:
    reloadStrategy: annotations
    readOnlyRootFileSystem: true
    deployment:
      image:
        name: registry.okd4.example.com:5010/stakater/reloader
      resources:
        requests:
          cpu: "10m"
          memory: "128Mi"
        limits:
          memory: "512Mi"
