apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: keda
  template:
    metadata:
      labels:
        app: keda
    spec:
      containers:
        - name: minimal
          image: ghcr.io/allbergkonsult/k8s-minimal-app:main
          args:
            - "-delay-ready=0"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              memory: 200Mi
          readinessProbe:
            httpGet:
              port: 8080
              path: /readyz
            periodSeconds: 2
          startupProbe:
            httpGet:
              port: 8080
              path: /readyz
            periodSeconds: 2
            timeoutSeconds: 60
            failureThreshold: 60
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
