apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podmonitor
spec:
  jobLabel: {{ .Release.Name }}
  selector:
    matchLabels:
      app: keda
  podMetricsEndpoints:
    - interval: 5s
      port: http
      path: /metrics
