{{- if and (.Capabilities.APIVersions.Has "autoscaling.k8s.io/v1") -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-app
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: app
  updatePolicy:
    minReplicas: 2
    updateMode: "Off"
{{- end -}}
