values_file: values.yaml

argo:
  project: addons
  target_revision: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io

cert_manager:
  use: true

reloader:
  use: true

ingressNginx:
  use: true

sealedSecrets:
  use: true

pvProviders:
  nfs:
    use: true
