ingressNginx:
  use: false

jaeger:
  use: true

keptn:
  use: true

kubecost:
  use: false

metricsServer:
  use: true

nginxIngress:
  use: false

prometheus:
  use: true
  podSecurityLevel: privileged

pvProviders:
  nfs:
    use: false
  csiDriverNFS:
    use: false

sealedSecrets:
  namespace: addon-sealed-secrets

trivy:
  use: false
