argo:
  project: addons
  common:
    valueFiles: []
    target_revision: main
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    apps_namespace: argocd
    enableLabelManagement: true

cert_manager:
  use: true
  podSecurityLevel: restricted

cert_manager_approver_policy:
  use: true

ingressNginx:
  use: true
  podSecurityLevel: baseline

kubecost:
  use: true
  podSecurityLevel: privileged

pvProviders:
  nfs:
    use: true
    podSecurityLevel: privileged

reloader:
  use: true
  podSecurityLevel: baseline

sealedSecrets:
  use: true
  namespace: kube-system
  podSecurityLevel: restricted
