apiVersion: v2
name: jaeger-operator
description: A Helm chart for Kubernetes

type: application

version: 2.54.0

dependencies:
  # Seems only searchable via helm
  - name: jaeger-operator
    version: 2.54.0
    repository: https://jaegertracing.github.io/helm-charts
