quota:
  use: false

upstream:
  reloader:
    reloadStrategy: annotations
    readOnlyRootFileSystem: true
    deployment:
      resources:
        requests:
          cpu: "10m"
          memory: "128Mi"
        limits:
          memory: "512Mi"
