upstream:
  isOpenshift: true
  reloader:
    serviceMonitor:
      enabled: true
    deployment:
      securityContext: false
      image:
        name: registry.okd4.example.com:5010/stakater/reloader
