{{ if .Values.okdComplianceOperator.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: okd-compliance-operator
  namespace: argocd
  finalizers:
{{ .Values.argo.finalizers | toYaml | indent 4 }}
spec:
  destination:
    namespace: openshift-compliance
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: okd-compliance-operator
      valueFiles:
        - {{ .Values.values_file }}
    path: okd-compliance-operator/
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
{{ end }}
