{{- if .Values.isOpenshift }}
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: grafana
  name: grafana-proxy
roleRef:
  kind: ClusterRole
  name: grafana-proxy
subjects:
  - kind: ServiceAccount
    name: grafana-instance-sa
    namespace: grafana
{{- end }}
