{{- if .Values.isOpenshift }}
apiVersion: rbac.authorization.k8s.io
kind: ClusterRoleBinding
metadata:
  name: grafana-proxy
roleRef:
  name: grafana-proxy
subjects:
  - kind: ServiceAccount
    name: grafana-instance-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
