argo:
  project: okd
  common:
    valueFiles: []
    target_revision: main
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    apps_namespace: argocd
    enableLabelManagement: true

catalogSources:
  use: true

certManager:
  use: false

complianceOperator:
  use: true
  podSecurityLevel: privileged

csrAutoApprover:
  use: true

garbageCollector:
  use: false
  podSecurityLevel: privileged

keda:
  use: true
  namespace: openshift-keda
  podSecurityLevel: restricted

kubecost:
  use: true
  podSecurityLevel: privileged

machineConfigs:
  use: true
  podSecurityLevel: restricted
patchOperator:
  use: true
  podSecurityLevel: restricted
