argo:
  project: okd
  common:
    valueFiles: []
    target_revision: main
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    apps_namespace: argocd

catalogSources:
  use: true
complianceOperator:
  use: true
garbageCollector:
  use: false
machineConfigs:
  use: true
patchOperator:
  use: true
