values_file: values.yaml

argo:
  project: okd
  target_revision: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  apps_namespace: argocd

patchOperator:
  use: true
catalogSources:
  use: true
complianceOperator:
  use: true
kubecost:
  use: true
machineConfigs:
  use: true
