{{ if .Values.pvProviders.nfs.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: {{ .Values.argo.common.apps_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- if .Values.argo.common.finalizers }}
  finalizers: {{ .Values.argo.common.finalizers | toYaml | nindent 4 }}
{{- end }}
spec:
  destination:
    namespace: addon-nfs-provisioner
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: nfs-provisioner
      {{- if .Values.argo.common.valueFiles }}
      valueFiles: {{ .Values.argo.common.valueFiles | toYaml | nindent 8 }}
      {{- end }}
    path: cluster-addons/pv-providers/nfs-subdir-external-provisioner/
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.common.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    {{- if .Values.argo.common.enableLabelManagement }}
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/audit: {{ .Values.pvProviders.nfs.podSecurityLevel }}
        pod-security.kubernetes.io/enforce: {{ .Values.pvProviders.nfs.podSecurityLevel }}
        pod-security.kubernetes.io/warn: {{ .Values.pvProviders.nfs.podSecurityLevel }}
    {{- end }}
{{ end }}
