{{ if .Values.pvProviders.nfs.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: {{ .Values.argo.apps_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
{{ .Values.argo.finalizers | toYaml | indent 4 }}
spec:
  destination:
    namespace: addon-nfs-provisioner
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: nfs-provisioner
      valueFiles:
        - {{ .Values.values_file }}
    path: cluster-addons/pv-providers/nfs-subdir-external-provisioner/
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
{{ end }}
