apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-cluster-monitoring-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: thanos-metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.triggerAuthentication.saName }}
    namespace: {{ .Release.Namespace }}
