{{ if .Values.addons.use }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: addons
  namespace: {{ .Values.argo.common.apps_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'addon-*'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
  sourceRepos:
    - '*'
{{- end -}}
