{{ if .Values.clusterAdmins.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-admins
  namespace: {{ .Values.argo.common.apps_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
{{ .Values.argo.finalizers | toYaml | indent 4 }}
spec:
  destination:
    namespace: cluster-admins
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: cluster-admins
      {{- if .Values.argo.common.valueFiles }}
      valueFiles: {{ .Values.argo.common.valueFiles | toYaml | nindent 8 }}
      {{- end }}
    path: cluster-admins/
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.common.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{ end }}
