{{ if .Values.okd.use }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: okd
  namespace: {{ .Values.argo.common.apps_namespace }}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'openshift-*'
      server: '*'
    - namespace: 'okd-*'
      server: '*'
  sourceRepos:
    - '*'
{{- end -}}
