{{ if .Values.okd.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: okd-start
  namespace: {{ .Values.argo.common.apps_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
{{ .Values.argo.finalizers | toYaml | indent 4 }}
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: okd-start
      {{- if .Values.argo.common.valueFiles }}
      valueFiles: {{ .Values.argo.common.valueFiles | toYaml | nindent 8 }}
      {{- end }}
      parameters:
        {{- include "template.helmParameters" (dict "prefix" "argo.common" "data" .Values.argo.common) | indent 8 }}
    path: okd/_start/
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.common.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
{{ end }}
