upstream:
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
    initContainerResources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi

    service:
      type: NodePort
      httpPort:
        nodePort: 30080
      httpsPort:
        nodePort: 30443

  prometheus:
    create: true
    service:
      create: true
    serviceMonitor:
      create: true
