upstream:
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
    initContainerResources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
