apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "isGateway": true,
      "master": "eno1",
      "mode": "bridge",
      "mtu": 1000,
      "name": "foobar",
      "type": "macvlan",
      "vlan": "43",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.61.0/24",
        "rangeStart": "192.168.61.30",
        "rangeEnd": "192.168.61.49",
        "routes": [
          { "dst": "192.168.61.0/24"},
          { "dst": "192.168.60.180/32"}
        ],
        "gateway": "192.168.61.1"
      }
    }'
