{{ if not .Values.isOpenshift }}
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: {{ .Release.Name}}-prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    access: proxy
    basicAuth: false
    editable: true
    isDefault: true
    name: Prometheus
    orgId: 1
    type: prometheus
    url: 'http://prometheus-kube-prometheus-prometheus.addon-prometheus.svc:9090'
{{- end }}
