{{- if not .Values.isOpenshift -}}
{{- if and (.Capabilities.APIVersions.Has "grafana.integreatly.org/v1beta1") -}}
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: {{ .Release.Name}}-grafana
  labels:
    dashboards: "grafana"
spec:
  client:
    preferIngress: false
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: "False"
      disable_signout_menu: "False"
      # The lifetime (days) an authenticated user can be inactive before being required to login at next visit. Default is 7 days.
      login_maximum_inactive_lifetime_duration: "1h"
      # The maximum lifetime (days) an authenticated user can be logged in since login time before being required to login. Default is 30 days.
      login_maximum_lifetime_duration: "1d"
      # How often should auth tokens be rotated for authenticated users when being active. The default is each 10 minutes.
      token_rotation_interval_minutes: "10"
    auth.anonymous:
      enabled: "True"
    security:
      admin_user: "admin"
      {{- if .Values.grafana.secretPassword }}
      admin_password: {{ .Values.grafana.secretPassword | quote }}
      {{- else }}
      admin_password: {{ randAlphaNum 24 | quote }}
      {{- end }}
{{- end }}
{{- end }}
