{{- if .Values.quota.use -}}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  {{ with .Values.quota.hard -}}
  hard:
  {{- toYaml . | nindent 4  }}
  {{- end -}}
{{- end -}}