apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: first-pool
  name: nginx
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.1.64
  clusterIPs:
    - 10.96.1.64
    - 2001:db8:42:1::fe28
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
    - IPv6
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: web
      #nodePort: 32011
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: web
    - name: websecure
      #nodePort: 32694
      nodePort: 30080
      port: 443
      protocol: TCP
      targetPort: websecure
  selector:
    app: nignx-waf
  sessionAffinity: None
  type: LoadBalancer
