apiVersion: v2
name: kubecost
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.99.0"

dependencies:
  # https://www.kubecost.com/install.html#show-instructions
  - name: cost-analyzer
    version: 1.99.0
    alias: upstream
    repository: https://kubecost.github.io/cost-analyzer/
