openshiftConfig:
  namespace: openshift-config
  serviceAccount:
    name: patch-operator-config
  clusterRole:
    name: patch-operator-cluster-config
  role:
    name: patch-operator-update-patches-in-ns
  OAuth:
    github:
      secret:
        name: github-okd-oauth-provider
      organizations:
        - "AyoyAB"
        - "AllbergKonsult"
monitoring:
  enableUserWorkload: true
machineConfigPools:
  patchLabels: true
registry:
  addCA: true
  restrict: true

egressIp:
  use: false
  clusterRoleName: egressip-patcher
  serviceAccount: egressip-patcher
  testNamespace: egressip-test
  hosts:
    - name: worker1.okd4.example.com
      subnets:
        - 192.168.60.0/24
  namespaces:
    - namespace: egressip-test
      egressIps:
        - 192.168.60.190

api:
  use: true
  clusterRoleName: api-patcher
  serviceAccount: api-patcher
