openshiftConfig:
  namespace: openshift-config
  serviceAccount:
    name: patch-operator-config
  clusterRole:
    name: patch-operator-cluster-config
  role:
    name: patch-operator-update-patches-in-ns
  OAuth:
    github:
      secret:
        name: github-okd-oauth-provider
      organizations:
        - "AyoyAB"
        - "AllbergKonsult"