{{- if and (.Capabilities.APIVersions.Has "compliance.openshift.io/v1alpha1") -}}
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: smuda
profiles:
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: TailoredProfile
    name: smuda-ocp4-cis
  - apiGroup: compliance.openshift.io/v1alpha1
    kind: TailoredProfile
    name: smuda-ocp4-cis-node
  - kind: Profile
    name: ocp4-moderate-node
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: smuda-default
{{- end }}
