{{- if .Values.whereabouts.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubi9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereabouts
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: "{{ .Values.whereabouts.definition.name }}"
      labels:
        app: whereabouts
    spec:
      containers:
        - name: samplepod
          command: [ "/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait" ]
          image: registry.access.redhat.com/ubi9:9.2-755.1697625012
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      nodeSelector:
        "kubernetes.io/hostname": master3.okd4.example.com
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end -}}
