{{- if and (.Capabilities.APIVersions.Has "compliance.openshift.io/v1alpha1") -}}
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: cis-compliance
profiles:
  - name: smuda-ocp4-cis-node
    kind: TailoredProfile
    apiGroup: compliance.openshift.io/v1alpha1
  - name: smuda-ocp4-cis
    kind: TailoredProfile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: smuda-default
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1
{{- end -}}
