apiVersion: v2
name: csi-driver-nfs
description: A Helm chart which installs the NFS subdirectory external provisioner

type: application

version: 4.5.0

dependencies:
  # https://github.com/kubernetes-csi/csi-driver-nfs/releases
  - name: csi-driver-nfs
    version: v4.11.0
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    alias: upstream
