apiVersion: v2
name: trivy-operator-install
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

dependencies:
  # https://github.com/aquasecurity/trivy-operator/releases
  - name: trivy-operator
    version: 0.25.0
    alias: upstream
    repository: https://aquasecurity.github.io/helm-charts/
