upstream:
  fullnameOverride: trivy-operator

  operator:
    metricsVulnIdEnabled: true
    scanJobsConcurrentLimit: 3 # Limit to three concurrent jobs. Default is 10.

  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  resources:
    requests:
      cpu: 10m
      memory: 1024Mi
    limits:
      cpu: 2
      memory: 3072Mi

  serviceMonitor:
    enabled: true

  trivy:
    ignoreUnfixed: true
    # -- resources resource requests and limits for scan job containers
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
        # ephemeralStorage: "2Gi"
      limits:
        cpu: 500m
        memory: 1000Mi
        # ephemeralStorage: "2Gi"

  trivyOperator:
    scanJobPodTemplatePodSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
