upstream:
  fullnameOverride: trivy-operator

  operator:
    logDevMode: true
    metricsVulnIdEnabled: true

  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  resources:
    requests:
      cpu: 10m
      memory: 600Mi
    limits:
      cpu: 1
      memory: 1024Mi

  serviceMonitor:
    enabled: true

  trivy:
    ignoreUnfixed: true

  trivyOperator:
    scanJobPodTemplatePodSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
