{{- $root := . -}}
{{- if .Values.security.usbGuard -}}
{{- range $mcpName := .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: {{ $mcpName }}
  name: 70-add-source-{{ $mcpName }}
spec:

  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/yum.repos.d/fedora-smuda.repo
          mode: 420
          overwrite: true
          contents:
            {{- $filecontent := $root.Files.Get "files/security/usbguard/70-fedora-smuda.repo" }}
            source: "data:;base64,{{ $filecontent | b64enc }}"
---
{{- end -}}
{{- end -}}
