namespace: addon-cert-manager

global:
  leaderElection:
    namespace: addon-cert-manager

quota:
  use: false

# Dependency values
upstream:
  installCRDs: false
  deploymentAnnotations:
    reloader.stakater.com/auto: "true"
  nameOverride: cert-manager
  extraArgs:
    # Disable standard approver, use policy approver instead
    - "--controllers=*,-certificaterequests-approver"
  namespace: addon-cert-manager
  image:
    repository: quay.io/jetstack/cert-manager-controller
  resources:
   requests:
     cpu: 100m
     memory: 128Mi
   limits:
     memory: 128Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

### webhook ###
  webhook:
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    image:
      repository: quay.io/jetstack/cert-manager-webhook
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true

    resources:
      requests:
        cpu: 100m
        memory: 96Mi
      limits:
        memory: 96Mi

### cainjector ###
  cainjector:
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    image:
      repository: quay.io/jetstack/cert-manager-cainjector
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 256Mi
  ### startupapicheck ###
  startupapicheck:
    image:
      repository: quay.io/jetstack/cert-manager-ctl
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 256Mi
