{{ if .Values.kro.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addon-kro-config
  namespace: {{ .Values.argo.common.apps_namespace }}
{{- if .Values.argo.common.finalizers }}
  finalizers: {{ .Values.argo.common.finalizers | toYaml | nindent 4 }}
{{- end }}
spec:
  destination:
    namespace: addon-kro
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    path: cluster-addons/kro-config/
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.common.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
{{ end }}
