{{ if .Values.ls24.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addon-kubecost
  namespace: {{ .Values.argo.common.apps_namespace }}
{{- if .Values.argo.common.finalizers }}
  finalizers: {{ .Values.argo.common.finalizers | toYaml | nindent 4 }}
{{- end }}
spec:
  destination:
    namespace: addon-ls24
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    path: cluster-addons/ls24/waf
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.common.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    {{- if .Values.argo.common.enableLabelManagement }}
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/audit: {{ .Values.ls24.podSecurityLevel }}
        pod-security.kubernetes.io/enforce: {{ .Values.ls24.podSecurityLevel }}
        pod-security.kubernetes.io/warn: {{ .Values.ls24.podSecurityLevel }}
    {{- end }}
{{ end }}
