{{ if .Values.openPolicyAgent.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-policy-agent
  namespace: argocd
  finalizers:
{{ .Values.argo.finalizers | toYaml | indent 4 }}
spec:
  destination:
    namespace: gatekeeper-system
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: gatekeeper
      valueFiles:
        - {{ .Values.values_file }}
    path: cluster-addons/open-policy-agent-gatekeeper/
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{ end }}
