apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: jaeger
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    access: proxy
    basicAuth: false
    database: ""
    editable: true
    isDefault: false
    jsonData: {"spanBar":{"type":"None"}}
    name: Jaeger
    orgId: 1
    type: jaeger
    url: http://simplest-query.{{ .Release.Namespace }}.svc.cluster.local:16686
    user: ""

