{{ if and .Values.networkpolicy.use (not .Values.isOpenshift) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress-grafana-ingress
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  ingress:
    - ports:
        - port: 9091
    # This really show be more restricted, but since its exposed via route anyway...
    - ports:
        - port: 3000
{{ end }}
