{{ if and .Values.kubeletConfigs.enabled .Values.kubeletConfigs.streamingConnectionIdleTimeout.enabled }}
{{- range $mcpName := .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: "enable-streaming-connections-{{ $mcpName }}"
  annotations:
    complianceascode.io/node-role: "{{ $mcpName }}"
spec:
  machineConfigPoolSelector:
    matchLabels:
      "pools.operator.machineconfiguration.openshift.io/{{ $mcpName }}": ""
  kubeletConfig:
    streamingConnectionIdleTimeout: 5m0s
---
{{- end }}
{{- end }}
