{{ if and .Values.kubeletConfigs.enabled .Values.kubeletConfigs.makeIPTablesUtilChains.enabled }}
{{- range $mcpName := .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: "enable-iptables-util-chains-{{ $mcpName }}"
spec:
  machineConfigPoolSelector:
    matchLabels:
      "pools.operator.machineconfiguration.openshift.io/{{ $mcpName }}": ""
  kubeletConfig:
    makeIPTablesUtilChains: true
---
{{- end }}
{{- end }}
