{{ if and .Values.kubeletConfigs.enabled .Values.kubeletConfigs.eventRecordQPS.enabled }}
{{- range $mcpName := .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: "event-creation-{{ $mcpName }}"
  annotations:
    complianceascode.io/node-role: "{{ $mcpName }}"
spec:
  machineConfigPoolSelector:
    matchLabels:
      "pools.operator.machineconfiguration.openshift.io/{{ $mcpName }}": ""
  kubeletConfig:
    eventRecordQPS: 5
---
{{- end }}
{{- end }}
