{{ if and .Values.machineConfigs.enableProtectKernelSysctl.enabled .Values.kubeletConfigs.enabled .Values.kubeletConfigs.protectKernelDefaults.enabled }}
{{- range $mcpName := .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: "protect-kernel-defaults-{{ $mcpName }}"
  annotations:
    # This has to be applied after 99-kubelet-enable-protect-kernel-sysctl
    # https://access.redhat.com/solutions/5957791
    argocd.argoproj.io/sync-wave: "9"
spec:
  machineConfigPoolSelector:
    matchLabels:
      "pools.operator.machineconfiguration.openshift.io/{{ $mcpName }}": ""
  kubeletConfig:
    protectKernelDefaults: true
{{- end }}
{{- end }}
