{{ if .Values.isOpenshift }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-binding
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name}}-grafana-sa
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-proxy
roleRef:
#  kind: ClusterRole
  name: grafana-proxy
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name}}-grafana-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
