argo:
  project: default
  common:
    valueFiles:
      - values.yaml
    target_revision: main
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    apps_namespace: argocd

addons:
  use: true

okd:
  use: false

clusterAdmins:
  use: true
