values_file: values.yaml


argo:
  project: default
  target_revision: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io

cert_manager:
  use: true

clusterAdmins:
  use: true

reloader:
  use: true

ingressNginx:
  use: true

sealedSecrets:
  use: true
okdCatalogSources:
  use: false
okdComplianceOperator:
  use: false
