apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-sync-job-sa-role
  #annotations:
    #argocd.argoproj.io/hook: PreSync
    #argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups:
      - apiextensions.k8s.io
      - machineconfiguration.openshift.io
    resources:
      - machineconfigpools
    verbs:
      - get
      - list
      - patch
      - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-sync-job-sa-rolebinding
  #annotations:
    #argocd.argoproj.io/hook: PreSync
    #argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-sync-job-sa-role
subjects:
  - kind: ServiceAccount
    name: mcp-sync-job-sa
    namespace: "{{ .Release.Namespace }}"
---
