hostLocal:
  enabled: false
  definition:
    name: hostlocal-macvlan

whereabouts:
  enabled: true
  definition:
    name: whereabouts-ipvlan


openshiftConfig:
  namespace: openshift-config
  serviceAccount:
    name: patch-operator-config # This is supposed to match the service account created in
                                # okd/config/templates/patch-operator-rights/serviceAccount.yaml
