apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

dependencies:
  # https://github.com/prometheus-community/helm-charts/releases
  - name: kube-prometheus-stack
    version: 52.1.0
    alias: upstream
    repository: https://prometheus-community.github.io/helm-charts
