{{ if .Values.csrAutoApprover.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: okd-csr-auto-approver
  namespace: {{ .Values.argo.common.apps_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- if .Values.argo.common.finalizers }}
  finalizers: {{ .Values.argo.common.finalizers | toYaml | nindent 4 }}
{{- end }}
spec:
  destination:
    namespace: openshift-config
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: csr-auto-approver
      {{- if .Values.argo.common.valueFiles }}
      valueFiles:
        {{- .Values.argo.common.valueFiles | toYaml | nindent 8 }}
        {{ with .Values.argo.common.additionalValueFiles }}
        {{ . | toYaml | nindent 8 }}
        {{ end }}
      {{- end }}
    path: okd/csr-auto-approver
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.common.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
{{ end }}
