{{ if .Values.kubecost.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: {{ .Values.argo.common.apps_namespace }}
{{- if .Values.argo.common.finalizers }}
  finalizers: {{ .Values.argo.common.finalizers | toYaml | nindent 4 }}
{{- end }}

spec:
  destination:
    namespace: okd-kubecost
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: kubecost
      {{- if .Values.argo.common.valueFiles }}
      valueFiles: {{ .Values.argo.common.valueFiles | toYaml | nindent 8 }}
      {{- end }}
    path: okd/kubecost/
    targetRevision: {{ .Values.argo.common.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
    {{- if .Values.argo.common.enableLabelManagement }}
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/audit: {{ .Values.kubecost.podSecurityLevel }}
        pod-security.kubernetes.io/enforce: {{ .Values.kubecost.podSecurityLevel }}
        pod-security.kubernetes.io/warn: {{ .Values.kubecost.podSecurityLevel }}
    {{- end }}
{{ end }}
