{{ if .Values.openshiftVerticalPodAutoscaler.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-vertical-pod-autoscaler-operator
  namespace: {{ .Values.argo.common.apps_namespace }}
{{- if .Values.argo.common.finalizers }}
  finalizers: {{ .Values.argo.common.finalizers | toYaml | nindent 4 }}
{{- end }}
spec:
  destination:
    namespace: openshift-vertical-pod-autoscaler
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: vertical-pod-autoscaler-operator
      {{- if .Values.argo.common.valueFiles }}
      valueFiles:
        {{- .Values.argo.common.valueFiles | toYaml | nindent 8 }}
        {{ with .Values.argo.common.additionalValueFiles }}
        {{ . | toYaml | nindent 8 }}
        {{ end }}
      {{- end }}
    path: okd/openshift-vertical-pod-autoscaler-operator/
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.common.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    {{- if .Values.argo.common.enableLabelManagement }}
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        pod-security.kubernetes.io/audit: {{ .Values.openshiftVerticalPodAutoscaler.podSecurityLevel }}
        pod-security.kubernetes.io/enforce: {{ .Values.openshiftVerticalPodAutoscaler.podSecurityLevel }}
        pod-security.kubernetes.io/warn: {{ .Values.openshiftVerticalPodAutoscaler.podSecurityLevel }}
    {{- end }}
{{ end }}
