{{ if .Values.sandboxedContainersConfig.use }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sandboxed-containers-operator
  namespace: {{ .Values.argo.common.apps_namespace }}
{{- if .Values.argo.common.finalizers }}
  finalizers: {{ .Values.argo.common.finalizers | toYaml | nindent 4 }}
{{- end }}
spec:
  destination:
    namespace: openshift-sandboxed-containers-operator
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      version: v3
      releaseName: garbage-collector
      {{- if .Values.argo.common.valueFiles }}
      valueFiles: {{ .Values.argo.common.valueFiles | toYaml | nindent 8 }}
      {{- end }}
    path: okd/sandboxed-containers-config/
    repoURL: https://github.com/smuda/home-cluster-argo.git
    targetRevision: {{ .Values.argo.common.target_revision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
{{ end }}
