{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-operator
spec:
  endpoints:
    - path: /metrics
      targetPort: metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/instance: addon-jaeger-operator
      app.kubernetes.io/name: jaeger-operator
{{- end -}}
