{{- if .Values.egressIp.use }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.egressIp.clusterRoleName }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - "network.openshift.io"
    resources:
      - netnamespaces
      - hostsubnets
    verbs:
      - get
      - list
      - watch
      - patch
{{- end }}
