apiVersion: v2
name: metrics-server
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

dependencies:
  # https://artifacthub.io/packages/helm/metrics-server/metrics-server
  - name: metrics-server
    version: 3.11.0
    alias: upstream
    repository: https://kubernetes-sigs.github.io/metrics-server/
