apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  image: registry.redhat.io/redhat/redhat-operator-index:v4.12
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
