{{ if and .Values.kubeletConfigs.enabled .Values.kubeletConfigs.autosizeReserved.enabled }}
{{- range $mcpName := .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: "autosize-reserved-{{ $mcpName }}"
spec:
  machineConfigPoolSelector:
    matchLabels:
      "pools.operator.machineconfiguration.openshift.io/{{ $mcpName }}": ""
  autoSizingReserved: true
---
{{- end }}
{{- end }}
