apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-custom-metrics-autoscaler-operator.openshift-keda: ""
  name: openshift-custom-metrics-autoscaler-operator
  namespace:  "{{ .Release.Namespace }}"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: keda
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: keda.v2.15.1
