apiVersion: v2
name: kubecost
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

appVersion: "1.105.2"

dependencies:
  - name: cost-analyzer
    repository: https://raw.githubusercontent.com/kubecost/openshift-helm-chart/main
    version: 1.105.2
