{
 "title": "keda-app-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "http_requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"okd-keda-app\"} [15s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{pod=~\"app-.*\",namespace=\"okd-keda-app\"})",
     "legendFormat": "ready"
    }
   ]
  },
  {
   "title": "Requests per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_requests_total{namespace=\"okd-keda-app\"} [15s])",
     "legendFormat": "{{pod}}"
    },
    { "expr": "5", "legendFormat": "Limit" }
   ]
  }
 ]
}