{{- $processedDict := dict -}}
{{- range $path, $bytes := .Files.Glob "policies/**" }}
{{- $name := base (dir $path) }}
{{- if not (hasKey $processedDict $name) -}}
{{ $_ := set $processedDict $name "true" }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: {{ $name }}
metadata:
  name: {{ $name | lower }}
spec:
  {{- $.Files.Get (printf "policies/%s/constraint.yaml" $name) | nindent 2 }}
---
{{- end }}
{{- end }}
