name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Find all charts
        run: |
          CHART_DIRS=$(find . -name Chart.yaml | sed -e "s/\/Chart.yaml//g" | sort)
          while IFS= read -r CHART_DIR; do
            echo ""
            echo "Building dependency"
            helm dependency build $CHART_DIR
            echo "Linting $CHART_DIR"
            helm lint $CHART_DIR
          done <<< "$CHART_DIRS"

#      - name: Create kind cluster
#        uses: helm/kind-action@v1.4.0
#        if: steps.list-changed.outputs.changed == 'true'

#      - name: Run chart-testing (install)
#        run: ct install
