name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Find all charts
        run: |
          CHART_DIRS=$(find . -name Chart.yaml | sed -e "s/\/Chart.yaml//g" | sort)
          while IFS= read -r CHART_DIR; do
            echo ""
            echo ""
            pushd $CHART_DIR
            echo "Find changes in Chart $CHART_DIR"
            changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
            if [[ -n "$changed" ]]; then
              echo "::set-output name=changed::true"
            fi
          
            echo ""
            echo "Linting $CHART_DIR"
            ct lint --target-branch ${{ github.event.repository.default_branch }}
            popd
          done <<< "$CHART_DIRS"

#      - name: Create kind cluster
#        uses: helm/kind-action@v1.4.0
#        if: steps.list-changed.outputs.changed == 'true'

#      - name: Run chart-testing (install)
#        run: ct install
