{{- $root := . -}}
{{- if .Values.system.chrony.enabled -}}
{{- range $mcpName := .Values.machineConfigPools }}
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: {{ $mcpName }}
  name: "99-chrony-{{ $mcpName }}"
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            {{- $filecontent := $root.Files.Get "files/system/chrony.conf" }}
            source: "data:;base64,{{ $filecontent | b64enc }}"
          mode: 420
          overwrite: true
          path: /etc/chrony.conf
---
{{- end -}}
{{- end -}}
