apiVersion: v2
name: start
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

dependencies:
  # https://github.com/argoproj/argo-helm/releases
  - name: argo-cd
    alias: argocd
    version: 9.2.1
    repository: https://argoproj.github.io/argo-helm
