apiVersion: v2
name: start
description: A Helm chart for Kubernetes

type: application

version: 1.0.0

dependencies:
  - name: argo-cd
    version: 6.7.10
    repository: https://argoproj.github.io/argo-helm
